# Generated by Django 2.1.8 on 2019-04-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commen',
            new_name='Comment',
        ),
    ]
